#!/usr/bin/env node
'use strict';
var args = process.argv.slice(2);
var hasUp = args.includes('-u') || args.includes('--up');
if (!hasUp) {
	process.argv.splice(2, 0, '-u', '1');
}
require('./copyfiles');